name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nargo
        uses: noir-lang/noirup@v0.1.2
        with:
          toolchain: nightly

      - name: Run Nargo test
        run: |
          cd circuits
          nargo test --show-output
