name: Circuit Gates
on:
  pull_request:
    branches: [main]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nargo
        uses: noir-lang/noirup@v0.1.2
        with:
          toolchain: nightly

      - name: Comment nargo info
        run: |
          cd circuits
          GATES=$(nargo info)
          gh pr comment $PR_NUMBER --body "<pre>$GATES</pre>" --edit-last
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
